[2022-01-04 14:45:45,731]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E4%B8%9C%E7%9C%81%E4%B8%9C%E8%8E%9E%E5%B8%82%E7%9F%B3%E9%BE%99%E9%95%87%E8%A5%BF%E6%B9%96%E7%A4%BE%E5%8C%BA%E7%8E%AF%E6%B9%96%E8%A5%BF%E8%B7%AF&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2022-01-04 14:45:45,761]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E5%B7%9E%E7%99%BD%E4%BA%91%E6%9C%BA%E5%9C%BA&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2022-01-04 14:45:45,812]-[baiduapi.py]-[get_driving_direction]-[137]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：出发点和目的地: 广东省东莞市石龙镇西湖社区环湖西路-------广州白云机场
[2022-01-04 14:49:31,932]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E4%B8%9C%E7%9C%81%E4%B8%9C%E8%8E%9E%E5%B8%82%E7%9F%B3%E9%BE%99%E9%95%87%E8%A5%BF%E6%B9%96%E7%A4%BE%E5%8C%BA%E7%8E%AF%E6%B9%96%E8%A5%BF%E8%B7%AF&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2022-01-04 14:49:31,967]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E5%B7%9E%E7%99%BD%E4%BA%91%E6%9C%BA%E5%9C%BA&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2022-01-04 14:49:31,969]-[baiduapi.py]-[get_driving_direction]-[137]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：出发点和目的地: 广东省东莞市石龙镇西湖社区环湖西路-------广州白云机场
[2022-01-04 14:49:48,156]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E4%B8%9C%E7%9C%81%E4%B8%9C%E8%8E%9E%E5%B8%82%E7%9F%B3%E9%BE%99%E9%95%87%E8%A5%BF%E6%B9%96%E7%A4%BE%E5%8C%BA%E7%8E%AF%E6%B9%96%E8%A5%BF%E8%B7%AF&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2022-01-04 14:49:48,187]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E5%B7%9E%E7%99%BD%E4%BA%91%E6%9C%BA%E5%9C%BA&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2022-01-04 14:49:48,189]-[baiduapi.py]-[get_driving_direction]-[137]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：出发点和目的地: 广东省东莞市石龙镇西湖社区环湖西路-------广州白云机场
[2022-01-04 15:54:46,492]-[baiduapi.py]-[get_place_accuracy_direction]-[206]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: list index out of range
[2022-01-04 15:54:52,627]-[baiduapi.py]-[get_driving_direction]-[137]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：出发点和目的地: -----------广州白云机场
[2022-01-04 15:55:17,950]-[baiduapi.py]-[get_driving_direction]-[174]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: 'address'
[2022-01-04 15:55:17,951]-[baiduapi.py]-[get_driving_direction]-[175]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：出发点和目的地: 增城-------广州白云机场
