[2021-12-17 16:12:30,683]-[object.py]-[<module>]-[299]-12s: [INFO]-8s>> ces
[2021-12-17 16:12:30,686]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> hello
[2021-12-17 16:15:30,226]-[object.py]-[<module>]-[299]-12s: [INFO]-8s>> ces
[2021-12-17 16:15:30,227]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> hello
[2021-12-17 16:27:01,022]-[object.py]-[<module>]-[299]-12s: [INFO]-8s>> ces
[2021-12-17 16:27:01,023]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> hello
[2021-12-17 16:39:11,230]-[object.py]-[get_apply_data]-[221]-12s: [ERROR]-8s>> request获取明细信息出错，错误单号：GA03-202111-46700：Unexpected Error: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[2021-12-17 16:50:40,817]-[object.py]-[<module>]-[299]-12s: [INFO]-8s>> ces
[2021-12-17 16:50:40,818]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> hello
[2021-12-17 16:50:49,376]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9AECB44C8>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:50:52,728]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:50:55,733]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9AECC3C88>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:50:55,734]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:30,728]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> ces
[2021-12-17 16:58:30,729]-[object.py]-[<module>]-[301]-12s: [INFO]-8s>> hello
[2021-12-17 16:58:32,681]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E5892DF48>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:58:32,682]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:33,505]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E58956F48>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:58:33,506]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:34,143]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E58956788>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:58:34,144]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:34,652]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E589610C8>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:58:34,652]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:35,107]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E5895C148>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:58:35,108]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:35,478]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027E5896DF88>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:58:35,479]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
[2021-12-17 16:58:54,280]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> ces
[2021-12-17 16:58:54,281]-[object.py]-[<module>]-[301]-12s: [INFO]-8s>> hello
[2021-12-17 16:59:07,525]-[object.py]-[getpagecontent]-[110]-12s: [ERROR]-8s>> requests加载用车申请列表信息出错！：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.Apply (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F1CE16648>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
[2021-12-17 16:59:10,459]-[object.py]-[getpagecontent]-[150]-12s: [ERROR]-8s>> 解析用车申请列表信息出错！：Unexpected Error: local variable 'response' referenced before assignment
