[2021-12-23 10:57:32,956]-[baiduapi.py]-[getplace_byabbreviation]-[139]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: float expected at most 1 arguments, got 2
[2021-12-23 10:57:36,180]-[baiduapi.py]-[getplace_byabbreviation]-[139]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: float expected at most 1 arguments, got 2
[2021-12-23 10:58:14,441]-[baiduapi.py]-[getplace_byabbreviation]-[139]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: float expected at most 1 arguments, got 2
[2021-12-23 15:31:08,195]-[baiduapi.py]-[get_place_accuracy_direction]-[200]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: list index out of range
[2021-12-23 15:31:09,315]-[baiduapi.py]-[get_driving_direction]-[169]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: 'NoneType' object is not subscriptable
[2021-12-23 15:31:28,857]-[baiduapi.py]-[get_place_accuracy_direction]-[200]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: list index out of range
[2021-12-23 15:31:31,931]-[baiduapi.py]-[get_driving_direction]-[169]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: 'NoneType' object is not subscriptable
[2021-12-23 16:42:28,570]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:42:28,570]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:42:28,571]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:42:28,571]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:42:29,620]-[CasSystemScrapy.py]-[insert_CasTravel]-[390]-12s: [ERROR]-8s>> 将派车单号GA-202112-4新增转化为sql出错：Unexpected Error: 0
[2021-12-23 16:42:29,620]-[CasSystemScrapy.py]-[insert_CasTravel]-[390]-12s: [ERROR]-8s>> 将派车单号GA-202112-4新增转化为sql出错：Unexpected Error: 0
[2021-12-23 16:43:19,965]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:43:19,965]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:43:19,965]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:43:19,965]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:46:40,212]-[CasSystemScrapy.py]-[insert_CasTravel]-[390]-12s: [ERROR]-8s>> 将派车单号GA-202112-4新增转化为sql出错：Unexpected Error: 0
[2021-12-23 16:46:40,212]-[CasSystemScrapy.py]-[insert_CasTravel]-[390]-12s: [ERROR]-8s>> 将派车单号GA-202112-4新增转化为sql出错：Unexpected Error: 0
[2021-12-23 16:47:05,665]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:47:05,665]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:47:05,666]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:47:05,666]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:49:46,465]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:49:46,465]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:49:46,466]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:49:46,466]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:49:56,069]-[baiduapi.py]-[get_place_accuracy_direction]-[200]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E4%B8%9C%E7%9C%81%E7%9F%B3%E9%BE%99%E9%95%87%E4%BA%AC%E7%93%B7%E8%B7%AF%E5%85%AB%E5%8F%B7&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-23 16:49:56,069]-[baiduapi.py]-[get_place_accuracy_direction]-[200]-12s: [ERROR]-8s>> 查询地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /place/v2/search?query=%E5%B9%BF%E4%B8%9C%E7%9C%81%E7%9F%B3%E9%BE%99%E9%95%87%E4%BA%AC%E7%93%B7%E8%B7%AF%E5%85%AB%E5%8F%B7&region=%E4%B8%9C%E8%8E%9E%E5%B8%82&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-23 16:50:19,095]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:50:19,095]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:50:19,096]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:50:19,096]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:53:47,527]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:53:47,527]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 16:53:47,528]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 16:53:47,528]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 17:01:19,183]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 17:01:19,183]-[CasSystemScrapy.py]-[<module>]-[645]-12s: [INFO]-8s>> ces
[2021-12-23 17:01:19,184]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 17:01:19,184]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> hello
[2021-12-23 17:19:30,243]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 17:19:30,243]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 17:19:30,244]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 17:19:30,244]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 17:19:39,865]-[baiduapi.py]-[get_driving_direction]-[169]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: list indices must be integers or slices, not str
[2021-12-23 17:19:39,865]-[baiduapi.py]-[get_driving_direction]-[169]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: list indices must be integers or slices, not str
[2021-12-23 17:20:36,190]-[CasSystemScrapy.py]-[insert_CasTravel]-[391]-12s: [ERROR]-8s>> 将派车单号GA-202112-4新增转化为sql出错：Unexpected Error: list index out of range
[2021-12-23 17:20:36,190]-[CasSystemScrapy.py]-[insert_CasTravel]-[391]-12s: [ERROR]-8s>> 将派车单号GA-202112-4新增转化为sql出错：Unexpected Error: list index out of range
[2021-12-23 18:06:47,304]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:06:47,304]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:06:47,305]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:06:47,305]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:11:59,814]-[baiduapi.py]-[get_driving_direction]-[169]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: list indices must be integers or slices, not str
[2021-12-23 18:11:59,814]-[baiduapi.py]-[get_driving_direction]-[169]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: list indices must be integers or slices, not str
[2021-12-23 18:12:00,586]-[CasSystemScrapy.py]-[insert_CasTravel]-[391]-12s: [ERROR]-8s>> 将派车单号GA-202112-2新增转化为sql出错：Unexpected Error: list index out of range
[2021-12-23 18:12:00,586]-[CasSystemScrapy.py]-[insert_CasTravel]-[391]-12s: [ERROR]-8s>> 将派车单号GA-202112-2新增转化为sql出错：Unexpected Error: list index out of range
[2021-12-23 18:12:02,905]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:12:02,905]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:12:21,584]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:12:21,584]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:12:21,585]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:12:21,585]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:15:05,416]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:15:05,416]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:15:18,864]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:15:18,864]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:15:18,865]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:15:18,865]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:15:19,970]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:15:19,970]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:15:46,483]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:15:46,483]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:15:46,483]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:15:46,483]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:15:47,857]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:15:47,857]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:16:09,866]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:16:09,866]-[CasSystemScrapy.py]-[<module>]-[646]-12s: [INFO]-8s>> ces
[2021-12-23 18:16:09,867]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:16:09,867]-[CasSystemScrapy.py]-[<module>]-[647]-12s: [INFO]-8s>> hello
[2021-12-23 18:16:11,147]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-23 18:16:11,147]-[CasSystemScrapy.py]-[get_apply_data]-[629]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
